version: '3.8'

services:
  tva-landing:
    build: .
    container_name: tva-landing-web
    ports:
      - "8090:8090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=8090
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=BHAVIN467
      - DB_NAME=tva_db
      - TABLE_PREFIX=tva_
      - NODE_ENV=production
    restart: always
